[package]
name = "timo"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["cargo", "derive"] }
dirs = "5.0.1"
rusqlite = { version = "0.32.1", features = ["bundled"] }
