[package]
name = "timo"
version = "0.2.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["cargo", "derive"] }
dirs = "5.0.1"
refinery = { version = "0.8.14", features = ["rusqlite-bundled"] }
rusqlite = { version = "0.31.0", features = ["bundled"] }
